### ISSUE TITLE
Fused Delta+BitPacking

### ISSUE THREAD

**Issue by gatesn** [cwida/FastLanes#2]
First of all, thank you for the incredible work! I'm currently working on an implementation of FastLanes over here in Rust: https://github.com/spiraldb/fastlanes

I came across this in Section 3.1:  

> *Fusing Bit-packing and Decoding*
 The 116 bit-unpacking kernels we generate for all bit-packing widths 𝑊 and unpacked type-widths 𝑇 ≤ 𝑊 could possibly be fused with the decoding kernel for DELTA, FOR, DICT and FastLanes-RLE in a single kernels that do both unpacking and decoding.

I have currently implemented BitPacking, FOR and Delta encodings. I am also able to implement a fused FOR+BitPacking. But I noticed there isn't an implementation of fused Delta+BitPacking in this repository.
 
My assumption is that a fused kernel is purely a runtime optimisation, meaning that the serialised bytes should remain unchanged. In other words, `BitPack(Delta(Transpose(Tuples)))` == `BitPack+Delta(Transpose(Tuples))`

You'll have to forgive me if my understanding is wrong here, but I don't think it's possible to write this kernel in a fused way (or at least, it's very difficult?) given the current implementation of BitPacking.

Taking u16 as a concrete example.

The element iteration order within the [delta encoding (unrsum) kernel](https://github.com/cwida/FastLanes/blob/5feb61d3b5078e5499690b51b30bd9a94556ccf6/fls_generated/fallback/scalar_av_uf1/fallback_scalar_av_1024_uf1_unrsum_src.cpp#L64-L126) (assuming a transposed input vector) is: 

```
[
  0 128 256 ... 768 896 
  64 192 320 ... 832 960
]
```

But the [element iteration order for BitPacking](https://github.com/cwida/FastLanes/blob/main/fls_generated/fallback/scalar_av_uf1/fallback_scalar_av_1024_uf1_unpack_src.cpp#L413-L449) doesn't respect the "04261537" in the same way:

```
[
  0 64 128 ... 384 448 
  512 576 640 ... 896 960
]
```

For T=u16 and W=8, BitPacking would put elements 0 and 64 into a single packed value. But the Delta iteration order expects elements 0 and 128 to be "adjacent".

I think if BitPacking used the same iteration order as Delta, then it would be much simpler to implement fused kernels for transposed encodings, with no downside to linear encodings. Currently, given the layout of bits on disk, I think it's only really possible to implement fused kernels for linear encodings like FOR and ALP.

I may of course be completely misunderstanding this! Hopefully my question makes sense. It's quite hard to phrase things that refer to elements within transposed, folded and vectorised loops!

**Comment by azimafroozeh** [comment]
Hi,

Thanks, 

So yes, Kernel fusion is a runtime optimization and does not affect the layout. It reduces the LOAD and STORE instructions needed to load back the bit unpacked data into registers for further decoding. 

Fusing Delta + Bitpacking is not trivial and requires the reimplementation of the bitpacking module, and changing the order of decoding is not the only change. You also need to decode and keep two registers of bit unpacked data and ... 

If you have more questions, my email is azim@cwi.nl.
